	PROGRAM SELECT_MOHO_DEPTH
	IMPLICIT NONE
	REAL(4), ALLOCATABLE:: INPUTDATA(:,:)
	REAL(4), ALLOCATABLE:: LATITUDE(:), LONGITUDE(:), MOHODEPTH(:)
	REAL(4) LONGMIN, LONGMAX, LATMIN, LATMAX
	INTEGER ROWS, UNIT1, UNIT2, I, J, ALLOC_ERROR
	CHARACTER(50) INPUTFILE, OUTPUTFILE

! IMPORTANT - FOR EACH DATA, IT IS NECESSARY TO CHANGES THE NUMBER OF ROWS
! CRUST1.0 DATA = 258121 ROWS
! GEMMA DATA = 1034641 ROWS
! UIEDA DATA = 77361 ROWS
	ROWS = 77361
	LONGMIN = -45.
	LONGMAX = -40.
	LATMIN = -4.
	LATMAX = -1.

	ALLOCATE(INPUTDATA(ROWS,3),STAT = ALLOC_ERROR)
	ALLOCATE(LATITUDE(ROWS),STAT = ALLOC_ERROR)
	ALLOCATE(LONGITUDE(ROWS),STAT = ALLOC_ERROR)
	ALLOCATE(MOHODEPTH(ROWS),STAT = ALLOC_ERROR)
    
	UNIT1 = 11
!	INPUTFILE = "crust1_moho_depth.txt"
!	INPUTFILE = "gemma_crust.txt"
	INPUTFILE = "uieda_moho.txt"
	OPEN (UNIT = UNIT1, FILE = INPUTFILE)
	
	DO I = 1, ROWS
	    READ(UNIT1,*)(INPUTDATA(I,J), J = 1, 3)
	END DO
    
	CLOSE (UNIT = UNIT1)
	
	DO I = 1, ROWS
	LONGITUDE(I) = INPUTDATA(I,1)
	LATITUDE(I) = INPUTDATA(I,2)
	MOHODEPTH(I) = INPUTDATA(I,3)
	END DO
	
	UNIT2 = 22
	OUTPUTFILE = "out_moho.txt"
	OPEN (UNIT = UNIT2, FILE = OUTPUTFILE)

	DO I = 1, ROWS
	IF(LONGMAX >= LONGITUDE(I).AND.LONGMIN <= LONGITUDE(I)) THEN
	IF(LATMAX >= LATITUDE(I).AND.LATMIN <= LATITUDE(I)) THEN
		WRITE(UNIT2,*)LONGITUDE(I), LATITUDE(I), MOHODEPTH(I)
        END IF
	END IF
	END DO
	            
	DEALLOCATE(INPUTDATA, STAT = ALLOC_ERROR)
	DEALLOCATE(LONGITUDE, STAT = ALLOC_ERROR)
    	DEALLOCATE(LATITUDE, STAT = ALLOC_ERROR)
	DEALLOCATE(MOHODEPTH,STAT = ALLOC_ERROR)
	
	STOP
	END PROGRAM SELECT_MOHO_DEPTH
